name: CI Pipeline

on: [push, pull_request]

jobs:
  test-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true  

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Download model (alternative)
      run: |
        wget https://github.com/SoFa325/mushroom-classifier-webapp/raw/refs/heads/main/app/model_weights.pth
      if: false  

    - name: Upgrade pip
      run: |
        pip install --upgrade pip
      continue-on-error: true

    - name: Install project in editable mode
      run: |
        pip install -e .

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_test.txt
        
    - name: Add project to PYTHONPATH
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Create required directories
      run: |
        mkdir -p app/static/uploads
        mkdir -p app/static/test_images

    - name: Check for model weights file
      run: |
        if [ ! -f "app/model_weights.pth" ]; then
          echo "::error::Model file not found: app/model_weights.pth"
          exit 1
        fi

    - name: Run tests
      run: |
        pytest tests/ -v

    - name: Start application (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: |
        python -m app.main
